name: 3 - Auto Review Pull Request
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  automate-pullrequest:
    runs-on: ubuntu-latest
    steps:
      - name: Auto reviews branches
        uses: golfzaptw/action-auto-reviews-from-branches@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          EVENT_TYPE: APPROVE
          BRANCHES: dev*
          AUTHOR: github-actions[bot]
          MESSAGE: Nice approve from github bot.