name: Create Pull Request
on:
  push:
    branches: 
      - 'dev**'
jobs:
  open-pr-to-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Make changes to pull request here
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: main
          labels: auto-pr
          assignees: kmaximo
          reviewers: kmaximo
          draft: false              
      
      - name: output-url
        run: echo ${{steps.cpr.outputs.pull-request-url}}
      - name: output-number
        run: echo ${{steps.cpr.outputs.pull-request-number}}
      - name: output-has-changed-files
        run: echo ${{steps.cpr.outputs.pull-request-operation}}
      - name: output-has-changed-files
        run: echo ${{steps.cpr.outputs.pull-request-head-sha}}

