name: 2 -Create Pull Request
on:
  push:
    branches: 
      - 'dev**'
jobs:
  open-pr-to-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pull-request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          #source_branch: ""                                     # If blank, default: triggered branch
          destination_branch: "main"                            # If blank, default: main
          pr_title: "Pulling ${{ github.ref }} into main"       # Title of pull request
          pr_body: ":crown: *An automated PR*"                  # Full markdown support, requires pr_title to be set
          pr_template: ".github/PULL_REQUEST_TEMPLATE.md"       # Path to pull request template, requires pr_title to be set, excludes pr_body
          pr_reviewer: "kmaximo"                                 # Comma-separated list (no spaces)
          pr_assignee: "kmaximo"                                # Comma-separated list (no spaces)
          pr_label: "auto-pr"                                   # Comma-separated list (no spaces)
          pr_milestone: "Milestone PR"                           # Milestone name
          pr_draft: false                                        # Creates pull request as draft
          pr_allow_empty: true                                  # Creates pull request even if there are no changes
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: output-url
        run: echo ${{steps.open-pr.outputs.pr_url}}
      - name: output-number
        run: echo ${{steps.open-pr.outputs.pr_number}}
      - name: output-has-changed-files
        run: echo ${{steps.open-pr.outputs.has_changed_files}}

    #  - name: Approve Pull Request
    #    uses: juliangruber/approve-pull-request-action@v1.1.1
    #    with:
    #      github-token: ${{ secrets.GITHUB_TOKEN }}
    #      number: ${{steps.open-pr.outputs.pr_number}}


  automate-pullrequest:
    needs:
      - open-pr-to-main
    runs-on: ubuntu-latest
    steps:
      - name: Auto reviews branches
        uses: golfzaptw/action-auto-reviews-from-branches@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
          EVENT_TYPE: APPROVE
          BRANCHES: dev*
          AUTHOR: 'kmcosta'
          MESSAGE: Nice approve from github bot.
         
