name: Create Pull Request
on:
  push:
    branches: 
      - 'dev**'
jobs:
  open-pr-to-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Make changes to pull request here
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4.1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          assignees: kmaximo
          reviewers: kmaximo
      
      - name: output-url
        run: echo ${{steps.cpr.outputs.pull-request-url}}
      - name: output-number
        run: echo ${{steps.cpr.outputs.pull-request-number}}
      - name: output-has-changed-files
        run: echo ${{steps.cpr.outputs.pull-request-operation}}
      - name: output-has-changed-files
        run: echo ${{steps.cpr.outputs.pull-request-head-sha}}

      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash